# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for the Keylogger Finder Windows EXE.
# Build from the project root:  pyinstaller KeyloggerFinder.spec

a = Analysis(
    ['gui_main.py'],
    pathex=['.'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'keylogger_finder',
        'keylogger_finder.cli',
        'keylogger_finder.gui',
        'keylogger_finder.scanner',
        'keylogger_finder.signatures',
        'keylogger_finder.finding',
        'keylogger_finder.report',
        'keylogger_finder.platforms',
        'keylogger_finder.platforms.common_checks',
        'keylogger_finder.platforms.windows_checks',
        'keylogger_finder.platforms.linux_checks',
        'keylogger_finder.platforms.macos_checks',
        'keylogger_finder.ui',
        'keylogger_finder.ui.theme',
        'psutil',
        'rich',
        'rich.console',
        'rich.panel',
        'rich.table',
        'pyfiglet',
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        '_tkinter',
        'winreg',
        'ctypes',
        'ctypes.wintypes',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['matplotlib', 'numpy', 'PIL', 'cv2', 'scipy'],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='KeyloggerFinder',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,          # windowed — no black console box
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico',        # generated by build script before pyinstaller runs
)
