from __future__ import annotations

KNOWN_KEYLOGGER_NAMES: list = [
    "ardamax",
    "refog",
    "spyrix",
    "actual keylogger",
    "actualkeylogger",
    "revealer keylogger",
    "revealerkeylogger",
    "elite keylogger",
    "elitekeylogger",
    "perfect keylogger",
    "perfectkeylogger",
    "sniperspy",
    "wincam",
    "logkeys",
    "pykeylogger",
    "keyghost",
    "winspy",
    "spytech",
    "spector360",
    "spectorsoft",
    "kidlogger",
    "family keylogger",
    "familykeylogger",
    "all in one keylogger",
    "allinonekeylogger",
    "quick keylogger",
    "quickkeylogger",
    "iwantsoft",
    "keylogger pro",
    "keyloggerpro",
    "phonesheriff",
    "mspy",
    "flexispy",
    "hoverwatch",
    "keystroke spy",
    "keystrokespy",
    "invisible keylogger",
    "stealth keylogger",
    "handy keylogger",
    "handykeylogger",
    "netbull",
    "oktech keylogger",
    "blazingtools",
    "snake keylogger",
    "snakekeylogger",
    "404 keylogger",
    "404keylogger",
    "krakenkeylogger",
    "hawkeye keylogger",
    "hawkeyekeylogger",
    "agent tesla",
    "agenttesla",
    "xloader",
    "terralogger",
    "phoenix keylogger",
    "phoenixkeylogger",
    "zerodayrat",
    "zero day rat",
    "cocospy",
    "spyic",
    "thetruthspy",
    "the truth spy",
    "umobix",
    "cerberus",
    "ahmyth",
    "androrat",
    "spynote",
    "xnspy",
    "mobispy",
    "neospy",
    "theonespy",
    "the one spy",
    "clevguard",
    "spyhuman",
    "ownspy",
    "letmespy",
    "highster mobile",
    "highstermobile",
    "imonitorspy",
    "i monitor spy",
    "ikey monitor",
    "ikeymonitor",
    "snoopza",
    "reptilicus",
    "spy24",
    "spylive360",
]

SUSPICIOUS_KEYWORDS: list = [
    "keylog",
    "keystroke",
    "keycapture",
    "capturekeys",
    "keyhook",
    "hookkeyboard",
    "inputspy",
    "keysniffer",
    "stealthlogger",
    "silentlogger",
    "spyware",
    "monitorkeys",
    "screenlogger",
    "passstealer",
    "credstealer",
    "pwdlogger",
]
